# üß© SPRING BOOT APPLICATION CONFIGURATION
spring:
  application:
    name: chatapp
  profiles:
    active: dev
  # üóÑÔ∏è DATABASE CONFIGURATION
  datasource:
    url: postgresql://localhost:5432/chatapp_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # ‚öôÔ∏è JPA + HIBERNATE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database-platform: org.hibernate.dialect.PostgreSQLDialect