# üß© SPRING BOOT APPLICATION CONFIGURATION
spring:
  application:
    name: chatapp
  profiles:
    active: dev
  # üóÑÔ∏è DATABASE CONFIGURATION
  datasource:
    url: postgresql://chatapp_user:3gaooO6UVeqXfHmqYYtXkamMM418flWw@dpg-d47p11u3jp1c73c5mtig-a.oregon-postgres.render.com/chatapp_db_abmq
    username: chatapp_user
    password: 3gaooO6UVeqXfHmqYYtXkamMM418flWw
    driver-class-name: org.postgresql.Driver

  # ‚öôÔ∏è JPA + HIBERNATE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database-platform: org.hibernate.dialect.PostgreSQLDialect